### ISSUE TITLE
Portability in Doxyfile

### ISSUE THREAD

**Issue by dbaelde** [DrStrangelove42/DreamOfaRidiculousMan#5]
When I run `make doc` doxygen complains that `../Source` does not exist. The generated doc is empty.

I initialiy assumed it was a portability issue (`..\Source` vs `../Source`) but changing this does not fix the issue.

**Comment by vbonczak** [comment]
In fact in most OSes today, the UNIX path separator '/' is perfectly understood (even in templeOS), although Microsoft loves the backslash (or at least DOS, like \\\\Resource...). 
Thus the problem was unlikely to be about this, but it was for sure a problem of approach from Windows that was different than the one used in Linux : the _working directory_. From Windows Explorer, doxygen started from the directory containing _doxyfile_, and indeed for GNUMake, it was from the _Makefile_ directory.
